week4/timetracking/config/routes.rb
Rails.application.routes.draw do

	root :to=> 'projects#home'

resources :projects, only: [:index, :show, :new, :create] do 
	resources :time_entries, except: [:show]
end

end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

week4/timetracking/app/models/project.rb
class Project < ApplicationRecord
	has_many :time_entries

	# def self.clean_old
	# 	where("created_at > ?" , 365.days.ago)destroy_all
	# end
end

week4/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project
end

week4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	# these create the actions
	def home

      render 'home' # name of view template app/views/site/home.html.erb
	
	end

	def index 

		@projects = Project.all

	end

	def show

    	@project = Project.find_by(id: params[:id])
    	unless @project
    		render 'no_projects_found'
        end
    end

    def new

    	@project = Project.new

    end

    def create

    	@my_project = Project.new(
    	  :name => params[:project][:name],
    	  :description => params[:project][:description]
    	)

        @my_project.save

        redirect_to "/projects/#{@my_project.id}"
    end

end

week4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home

      render 'home' # name of view template app/views/site/home.html.erb
	
	end

	def email

      render 'email'

    end

    def say_name

      @name = params[:name]

      render 'say_name'

    end

end

week4/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController

	def edit

		@project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])

	end	

	def index

        @project = Project.find(params[:project_id])

        @time_entries = @project.time_entries.where(
     	date: Time.now.beginning_of_month..Time.now.end_of_month
     	)

	end

	def new

		@project = Project.find(params[:project_id])

		@time_entry = @project.time_entries.new

	end

	def create
		@my_project = Project.find(params[:project_id])
		time_entries = @my_project.time_entries.new(
			:hours => params[:time_entry][:hours],
			:minutes => params[:time_entry][:minutes],
			:comment =>params[:time_entry][:comment],
			:date => params[:time_entry][:date]
			)
		time_entries.save
    	

        redirect_to project_time_entries_path(@my_project)

	end	

	private

	    def time_entry_params
	    	params.require(:time_entry).permit(:hours, :minute, :date)
	    end	

		
end

week4/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render("other_stuff/header") %>

    <%= yield %>

    <footer>
      <p>Javier powered</p>
    </footer>
  </body>
</html>

week4/timetracking/app/views/time_entries/edit.html.erb
<h1>Editing time entries</h1>

<%= form_for [@project, @time_entry] do |f| %>
 	<%= f.label :hours %>
 	<%= f.text_field :hours %>
    <br>
 	<%= f.label :minutes %>
 	<%= f.text_field :minutes %>
    <br>
 	<%= f.label :date %>
 	<%= f.text_field :date %>
    <br> 
    <%= f.label :comment %>
 	<%= f.text_field :comment%>
    <br> 
 	<%= f.button "Save"%>
  <%end%>

week4/timetracking/app/views/time_entries/index.html.erb
<h2><%= @project.name %></h2>
<ul>
  <% @time_entries.each do |entry| %>
    <li>

     <%= entry.hours %> h

     <%= entry.minutes %> m

     <%= entry.date %>

    </li>

  <% end %>

</ul>

<%=link_to "New Time Entry",new_project_time_entry_path(@project)%>

week4/timetracking/app/views/time_entries/new.html.erb
<h2>New Time Entry</h2>

  <%= form_for [@project, @time_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
    <br>
    <%= f.label :minutes %>
	<%= f.text_field :minutes %>
    <br>
    <%= f.label :date %>
	<%= f.text_field :date %>
    <br>

    <%= f.submit "Save" %>
  <%end%>
    